version: '3.8'

services:
  bajaj-hackrx-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      # Azure OpenAI Configuration
      - AZURE_OPENAI_ENDPOINT=https://your-resource.openai.azure.com/
      - AZURE_OPENAI_API_KEY=your-azure-openai-key
      - AZURE_OPENAI_API_VERSION=2024-02-15-preview
      - AZURE_OPENAI_MODEL_DEPLOYMENT=gpt-4
      - AZURE_OPENAI_EMBEDDING_DEPLOYMENT=text-embedding-ada-002
      
      # Azure Cognitive Search Configuration
      - AZURE_SEARCH_ENDPOINT=https://your-search-service.search.windows.net
      - AZURE_SEARCH_API_KEY=your-search-key
      - AZURE_SEARCH_INDEX_NAME=document-chunks
      
      # Azure SQL Database Configuration
      - AZURE_SQL_SERVER=your-server.database.windows.net
      - AZURE_SQL_DATABASE=your-database
      - AZURE_SQL_USERNAME=your-username
      - AZURE_SQL_PASSWORD=your-password
      - AZURE_SQL_DRIVER=ODBC Driver 18 for SQL Server
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
