# Railway Nixpacks Configuration
providers = ["python"]

[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = ["pip install -r requirements_simple.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "python main.py"
