# Railway Configuration
# This file helps Railway understand how to deploy your app

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
PORT = "8000"
PYTHON_VERSION = "3.11"
NIXPACKS_PYTHON_VERSION = "3.11"
