# Railway Configuration for HackRX - Minimal Stable Setup
[deploy]
startCommand = "python main.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "never"

[variables]
PYTHONUNBUFFERED = "1"
