services:
  - type: web
    name: bajaj-hackrx-api
    env: python
    buildCommand: pip install -r requirements_simple.txt
    startCommand: python main.py
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.11.0
    autoDeploy: true
    branch: main
