# DISABLED: Azure App Service deployment - Using Railway instead
# This workflow has been disabled to prevent automatic Azure deployments
# The repository is now configured for Railway deployment only

name: Deploy to Azure App Service (DISABLED)

# Disable automatic triggers by commenting out the 'on' section
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# Manual trigger only (if needed for testing)
on:
  workflow_dispatch:
    inputs:
      deploy_environment:
        description: 'Deployment environment'
        required: true
        default: 'test'
        type: choice
        options:
        - test
        - disabled

jobs:
  build:
    runs-on: ubuntu-latest
    # Disable this job - Railway deployment is used instead
    if: false

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python version
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Create and start virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: |
        pip install -r requirements_simple.txt

    - name: Upload artifact for deployment jobs
      uses: actions/upload-artifact@v3
      with:
        name: python-app
        path: |
          . 
          !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    # Disable this job - Railway deployment is used instead
    if: false
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: python-app
        path: .

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      id: deploy-to-webapp
      with:
        app-name: 'bajaj-hackrx'
        slot-name: 'Production'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        package: .
